### ISSUE TITLE
Question related to the project structure

### ISSUE THREAD

**Issue by robertotru** [jonashackt/spring-boot-vuejs#10]
Hi Jonas,

Good morning.

First, let me thank you for sharing this project example.
I started having a look at the project an I need a couple of clarifications.

1. If the frontend is served by _Vue.js_ on port 8080, what is the purpose of copying all the static resources in the backend? Asserts will be served by _NodeJs_ and _SpringBoot_ should be used for REST calls only. What am I missing?
2. However, supposing this approach is ok, it would not make sense to dockerize backend and frontend separately, since te backend will not be decoupled from the frontend. Am I right?

Thanks a lot for your time.
Best regards
Roberto

**Comment by jonashackt** [comment]
Hi @robertotru, glad to hear that the project helps you!

The frontend is served by the Spring Boot backend, therefore all the frontend assets are copied to the Spring Boot backend and all together is served on port 8088 (or whatever port you might configure at the [application.properties](https://github.com/jonashackt/spring-boot-vuejs/blob/master/backend/src/main/resources/application.properties) ). Thus you can easily Dockerize the app.

Only for development purposes, the frontend could be launched seperately via webpack with `npm run dev`, which will serve the Vue-Frontend in a developer-friendly way (hot reloading of the whole toolchain with webpack devserver) on port 8080.

Hope this clarifies things for you. I close this ticket now.
