### ISSUE TITLE
Changes from frontend does not apply to backend 

### ISSUE THREAD

**Issue by mystermiam** [jonashackt/spring-boot-vuejs#14]
Hello, 

I 've built a project based on your process and i don't succeed to see any of the changes made in front when i launch the app with spring boot. Could you help with that ? It's not an issue per se, but you're the only one i've found giving some content on how to integrate vue with a java environment.

**Comment by guillevc** [comment]
I'm also building a project based on this. `npm run build` is only executed if you run `mvn install` on the root pom or frontend pom. So if you start your Spring Boot application or run `mvn install` on the backend project the frontend files are just copied in the `generate-resources` phase but not built.

**Comment by mystermiam** [comment]
Thanks for the reply, indeed, it worked as expected by running "mvn install" on the project root. Actually, when running  "mvn install " just on the backend, it did not worked. Sources were not copied besides running "build" manually. Thanks for the insights. Do you know if there is a way to launch the project with spring boot and for it  to build and copy automatically ? 

I'm new to maven as anything other than a dependency manager tool so any help would be appreciated.

**Comment by mystermiam** [comment]
Alright, i found what i was looking for. To do so, i 've modified the backend pom.xml by addind this piece to at the top plugins' build tag section.

    <build>
      <plugins>
         <plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                <version>1.5</version>
                <executions>
                    <execution>
                        <id>npm run build</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <configuration>
                        	<workingDirectory>${project.parent.basedir}/frontend</workingDirectory>
                            <arguments>run build</arguments>
                        </configuration>
                    </execution>
                </executions>
         </plugin>
          ....

Feel free to signal if there is a better way but to me it does the job.

**Comment by jonashackt** [comment]
@mystermiam @guillevc I think you are referring to the local development process of your app!? There you **don´t**  need to extend the backend pom.xml.

Instead you can use the webpack-dev-server to achieve [a fast feedback development cicle](https://github.com/jonashackt/spring-boot-vuejs#fast-feedback-with-webpack-dev-server). Just cd into the frontend folder and run `npm run dev`. This will run the [webpack-dev-server](https://webpack.js.org/configuration/dev-server/), open your Browser and reflect Vue.js code changes immediately. 

Additionally - if you want to change the Spring Boot backend - you fire up your main Application class (like the [SpringBootVuejsApplication.java](https://github.com/jonashackt/spring-boot-vuejs/blob/master/backend/src/main/java/de/jonashackt/springbootvuejs/SpringBootVuejsApplication.java) ) inside your IDE (I use IntelliJ here). Having the spring-boot-devtools in the backend pom.xml, any change to your Java codebase will also reflect after a fast automatic restart of the Spring Boot backend.

There will be a blog post about all the integration aspects of Spring Boot and Vue.js comming next week on https://blog.codecentric.de/en/ - stay tuned :)

**Comment by mystermiam** [comment]
Alright, thanks for your advices. 

The thing that bothered me was that it felt like it's out of sync (between front and back) when launching the backend. I'm currently working on oauth authentification and for my peace of mind, i prefer have it sync so i could test the authentification for some reason. I know i'm missing something there with the sop thing. It will be clearer when i'm done with mastering vue router and this environment. 

Thanks again
