### ISSUE TITLE
[Question] gradle support

### ISSUE THREAD

**Issue by ehhc** [jonashackt/spring-boot-vuejs#20]
Are there any plans to redo the project with gradle?

**Comment by ehhc** [comment]
I think you're right, that it is not a good idea.
I just hoped someome already did it and you may know about it.. :D

**Comment by supernovel** [comment]
I wrote it. But I do not know Gradle well. I wish I could be a help. (help by google translater)
https://github.com/supernovel/spring-boot-vuejs
