### ISSUE TITLE
How to deploy on tomcat?

### ISSUE THREAD

**Issue by vacolane** [jonashackt/spring-boot-vuejs#22]
Hello,
I've created a project following this model, the maven build works great, I can start it with the embeded spring boot tomcat server. But I have no idea how I could export it to something then deploy it on a tomcat server, anyone can help me?

**Comment by jonashackt** [comment]
Hi @vacolane - first question: why do you want to deploy a Spring Boot app to a Tomcat application server? Spring Boot brings the embedded Tomcat and you can use it right as a Microservice. 

If you have a real good answer for the first question, just have a look at the Spring Boot docs, which cover this topic quite well - e.g. see https://www.baeldung.com/spring-boot-war-tomcat-deploy

**Comment by Karlinna** [comment]
I still would need this. In the current situation I'm working on we would deploy (host) war packages on tomcat servers (organization standard) and somehow I need to wrap in the UI made in Vue.JS and the REST API Service.

I didn't want to open a new ticket.

Chances are we would run UI on different service/server though but I wanted to give it a try.

**Comment by jonashackt** [comment]
I think, I don't really get the question or the goal you pursuit... what would be the thing you really need from this project here? Deployment of Spring Boot into a Tomcat is covered from other guides like the mentioned https://www.baeldung.com/spring-boot-war-tomcat-deploy. You could deploy the Vue.js UI components also into the .war deployment - or simply deploy it somewhere else. But as said, this seems to be far out of this project's scope.
