### ISSUE TITLE
Can't load assets

### ISSUE THREAD

**Issue by beraylik** [jonashackt/spring-boot-vuejs#32]
I have a problem when the app doesn't load resources with the 404 Error
![2018-09-26 11 31 26](https://user-images.githubusercontent.com/22113339/46067572-d39ba380-c17f-11e8-9bd2-c397c952a2a0.png)

It happens when I try to connect to the app via static address.

When Im connecting on localhost everything  is OK

In this example im using the stock app just cloned from repo, and there is this problem

**Comment by jonashackt** [comment]
What do you mean by " I try to connect to the app via static address."? Do you run the whole app using Maven `mvn spring-boot:run` or did a Maven build separately using `mvn clean install` and then starting the full app with `java -jar backend/target/backend-0.0.1-SNAPSHOT.jar`?
