### ISSUE TITLE
No instructions on how to run front-end in production

### ISSUE THREAD

**Issue by myxibrium** [jonashackt/spring-boot-vuejs#33]
I assumed that the jar file produced by the front-end project was an executable jar file. But then I realized it is not. It would be nice to have an executable jar. Or at least some explicit instructions on how you intend to run this in production.

**Comment by myxibrium** [comment]
Ah, I just realized that the backend.jar contains the front-end. Now I feel like an idiot.

**Comment by jonashackt** [comment]
No problem, if you have an idea on how we can clarify that point, please submit a PR. I'll close this now 😃
