### ISSUE TITLE
Secure with Spring Security & protect Vue frontend part incl. Login

### ISSUE THREAD

**Issue by paulvi** [jonashackt/spring-boot-vuejs#35]
Could here be extending to show how to secure with Spring Security and configure Vue.js to work together?

Are you aware of example for that?

**Comment by jonashackt** [comment]
Good point, we should have an example implementation for this topic. But I don't know, when I will have the time for it, PRs always welcome :)

**Comment by jonashackt** [comment]
Hey @paulvi a simple implementation of a secured backend resource is now included - together with a protected frontend part. Have fun!

**Comment by jonashackt** [comment]
We should also have a solution how to check on a secured part in the backend, whether the user was already logged in before successfully - because with the current solution, only the frontend (vuex store) knows this "auth state".

**Comment by jonashackt** [comment]
Simply storing the credentials inside vuex store and submitting them with every backend call from the frontend should do the trick (and help https://github.com/digital-bauhaus/Ferienpass/issues/27 without the need to build a user management, registration system with JWT tokens)

**Comment by paulvi** [comment]
We did using Basic Authentication (and TLS secured connections)

Note that JWT is stateless, so there is no sessions on server, it may be good or bad.  
And it was unacceptable for our case.

JWT is also not the only token possible, there were too many ways before.
