### ISSUE TITLE
[Question] Manage server side static resources

### ISSUE THREAD

**Issue by guillevc** [jonashackt/spring-boot-vuejs#36]
Where would you place server side public static content like images. Right now the whole vuejs app is inside public. what's the best option? move the app to a subfolder and then create resources/public/images? or just create the folder in the same folder as the webapp. 
it may be a stupid question. thanks for the work!

**Comment by jonashackt** [comment]
Hi @guillevc - I think that is more a general design question for your specific project. For me, this example projects shows a fully working solution to start with. I guess, storing many images the way this project shows isn't suitable for larger projects - there you'll may need to integrate CDNs (https://de.wikipedia.org/wiki/Content_Delivery_Network). I would advice you to do some research and find the best solution for your situation. I'll close this here as this is off topic.
