### ISSUE TITLE
external packages can't be added to backend

### ISSUE THREAD

**Issue by Rakesh49** [jonashackt/spring-boot-vuejs#39]
how to add  external jars to backend. Backend is not recognised as a java project in eclipse.

**Comment by jonashackt** [comment]
Hi, this project is based on [Apache Maven](https://maven.apache.org/). Just add your needed dependencies into the [backend/pom.xml](https://github.com/jonashackt/spring-boot-vuejs/blob/master/backend/pom.xml).

**Comment by Rakesh49** [comment]
When added some external jars to backend, It working fine on eclipse but upon running the jar in the target folder. these external jars becomes inaccessible

**Comment by jonashackt** [comment]
Seems to be out of this projects' scope, try to file a question of stackoverflow instead :)
