### ISSUE TITLE
Build issue with node-sass: Node Sass could not find a binding for your current environment

### ISSUE THREAD

**Issue by vikumDheemantha** [jonashackt/spring-boot-vuejs#47]
I tried to use the same implementation with nuxt.js which is vue.js framework. all went fine until I include `node-sass` and # to compile 'scss' styles.

After that when I tried to `mvn clean install`. It stops at `npm run generate` with error `Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 12.x`. But when I tried to build it with manually in frontend using the command `npm run generate`. It works fine.

How can I solve this problem?

**Comment by jonashackt** [comment]
Hey @vikumDheemantha please try google -> you'll find such things there: https://stackoverflow.com/a/48974815/4964553
