### ISSUE TITLE
Favicon from vue

### ISSUE THREAD

**Issue by abondar24** [jonashackt/spring-boot-vuejs#49]
Hey guys,

It is not actually an issue, rather a question. How did you managed to replace default spring favicon  with vue one?  For my project I tried everything but it is still a spring one

**Comment by jonashackt** [comment]
Hi @abondar24, in the Maven build process, all the Vue.js frontend sources are build to classic .html, .css and .js files with the help of webpack & npm. Coming from a standard Vue.js template, these also contain a favicon.ico file. All these files are copied from the `/frontend` directory to `/backend/src/main/resources/public/favicon.ico` (see docs https://github.com/jonashackt/spring-boot-vuejs#backend) - that's all I did. Inside the generated `index.html` there's this line:

```
<link rel=icon href=/favicon.ico>
```

I guess, that's all the "magic". If you want to dive deeper into the topic, use Dr. google :)
