### ISSUE TITLE
npm run build not working on windows

### ISSUE THREAD

**Issue by xkuyax** [jonashackt/spring-boot-vuejs#6]
Hi, im trying to get your example working. I cloned your git repository, and tried to run mvn clean install, which does not work on my system. I looked at the other issue and changed the npm version to 5.0.4 but it is still failing.

Here is my error log 
https://hastebin.com/ifegujapar.tex
npm debug log 
https://hastebin.com/xiwuhahatu.tex

Any ideas?

**Comment by jonashackt** [comment]
<img width="1033" alt="win10-testbuild" src="https://user-images.githubusercontent.com/6949966/33668036-da7b25a4-da9e-11e7-81c4-1e83f3119685.png"> I´am experiencing the same error with Windows 10. I think, there´s a problem with the npm version on Windows - I thought, that should be gone with the help of a downgrade of npm (see https://github.com/jonashackt/spring-boot-vuejs/issues/1). But I also get that error with the `5.0.4` on Windows 10, so I guess that needs further investigation. 

Please feel free to submit pull requests for that - I don´t have much time for that atm.

**Comment by jonashackt** [comment]
Ok, I´ll close this for now. Please open again, if the issue remains.
