### ISSUE TITLE
Innecessary @RequestBody annotations on @RestController-annotated controllers

### ISSUE THREAD

**Issue by guillevc** [jonashackt/spring-boot-vuejs#60]
We don't need to annotate the @RestController-annotated controllers with the @ResponseBody annotation since it's done by default.

https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/bind/annotation/RestController.html

**Comment by jonashackt** [comment]
The controller is annotated with `@RequestMapping` - or do you mean the methods? How should that work? PRs always welcome...

**Comment by jonashackt** [comment]
Fixed by @luanelioliveira 👍
