### ISSUE TITLE
After starting tomcat got 404 @main page 

### ISSUE THREAD

**Issue by TingtingGu2014** [jonashackt/spring-boot-vuejs#8]
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Tue Jan 09 16:30:53 CST 2018
There was an unexpected error (type=Not Found, status=404).
No message available

**Comment by jonashackt** [comment]
Do you have any more background info, you can provide @TingtingGu2014 ? I don´t see a 404, when I start the app with a `java -jar app.jar` command or inside the IDE, when I point my browser to http://localhost:8088/#/

**Comment by drahkrub** [comment]
This happen if `mvn --projects backend spring-boot:run` is not preceeded by `mvn clean install`.

**Comment by jonashackt** [comment]
Uh, well if that´s the problem... 😃 ?!? Would be more related to "how to use a Maven based project"...
