### ISSUE TITLE
Port should be 8080 instead of 8888

### ISSUE THREAD

**Issue by dwschulze** [jonashackt/spring-boot-vuejs#85]
"Now go to http://localhost:8088/ and have a look at your first Vue.js Spring Boot App."

should be port 8080.

**Comment by guillevc** [comment]
Spring Boot backend runs on 8088
Vue's webpack-dev-server runs on 8080

That statement is in First App Run section, where you launch your full Spring Boot app, which serves the built Vue.js app. So accessing from 8088 is correct.

**Comment by atelles** [comment]
Spring Boot backend is running on port 8089 on Master, but the Readme is only referencing port 8088

**Comment by guillevc** [comment]
> Spring Boot backend is running on port 8089 on Master, but the Readme is only referencing port 8088

You're right they are inconsistencies right now. I'm making a PR to fix this.

**Comment by jonashackt** [comment]
Thanks for clarifying @guillevc 👍
